project:
  type: website

website:
  title: "helpdesk"  
  site-url: "https://vuw-scps.github.io/helpdesk"
  page-footer: 
    center: "Copyright 2023, SCPS" 
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: python.qmd
        text: Python resources
      - href: R.qmd
        text: R resources
    right:
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/vuw-scps/helpdesk

format:
  html:
    theme: litera
    css: styles.css
    toc: true



